export const FETCH_DASHBOARD_API = 'FETCH_DASHBOARD_API';
export const FETCH_TOPFIVE_API = 'FETCH_TOPFIVE_API';
export const FETCH_SUMMARY_API = 'FETCH_SUMMARY_API';
export const FETCH_TIMELINE_API = 'FETCH_TIMELINE_API';