export const indiaDashBoard = {
      'confirmed':{value: 'Confirmed', delta:'Delta_Confirmed', title:'Confirmed' },
      'active': {value:'Active', delta:null, title:'Active' },
      'recovered':{value:'Recovered', delta:'Delta_Recovered', title:'Recovered' }, 
      'deceased':{value:'Deaths', delta:'Delta_Deaths', title:'Deceased' },
};
export const worldDashBoard = {
      'confirmed':{value:'confirmed_g', delta:'confirmed_g_diff', title:'Confirmed' },
      'active': {value:'active_g', delta:null, title:'Active' },
      'recovered':{value:'recovered_g', delta:'recovered_g_diff', title:'Recovered' }, 
      'deceased':{value:'death_g', delta:'death_g_diff', title:'Deceased' },
};
export const KPIHeader = {
      "State_confirmed_rate": "Confirmed per million",
      "State_recovery_rate": "Recovery Rate",
      "State_death_rate": "Death Rate",
      "State_positivity_rate": "Positivity Rate",
      "State_testing_rate": "Testing per million",
      "State": "Confirmed cases"};
      
export const mapDataJson = [
      { id: 'AP', state: 'Andhra Pradesh', value: 0 },
      { id: 'AR', state: 'Arunachal Pradesh', value: 0},
      { id: 'AS', state: 'Assam', value: 0 },
      { id: 'BR', state: 'Bihar', value: 0 },
      { id: 'CT', state: 'Chhattisgarh', value: 0},
      { id: 'GA', state: 'Goa', value: 0 },
      { id: 'GJ', state: 'Gujarat', value: 0 },
      { id: 'HR', state: 'Haryana', value: 0 },
      { id: 'HP', state: 'Himachal Pradesh', value: 0 },
      { id: 'JH', state: 'Jharkhand', value: 0 },
      { id: 'KA', state: 'Karnataka', value: 0 },
      { id: 'KL', state: 'Kerala', value: 0 },
      { id: 'MP', state: 'Madhya Pradesh', value: 0},
      { id: 'MH', state: 'Maharashtra', value: 0 },
      { id: 'MN', state: 'Manipur', value: 0 },
      { id: 'ML', state: 'Meghalaya', value: 0 },
      { id: 'MZ', state: 'Mizoram', value: 0 },
      { id: 'NL', state: 'Nagaland', value: 0 },
      { id: 'OD', state: 'Odisha', value: 10 },
      { id: 'PB', state: 'Punjab', value: 0 },
      { id: 'RJ', state: 'Rajasthan', value: 0 },
      { id: 'SK', state: 'Sikkim', value: 0 },
      { id: 'TN', state: 'Tamil Nadu', value: 0},
      { id: 'TG', state: 'Telangana', value: 0 },
      { id: 'TR', state: 'Tripura', value: 0 },
      { id: 'UK', state: 'Uttarakhand', value: 0 },
      { id: 'UP', state: 'Uttar Pradesh', value: 0 },
      { id: 'WB', state: 'West Bengal', value: 0 },
      { id: 'WB', state: 'West Bengal', value: 0 },
      { id: 'AN', state: 'Andaman and Nicobar Islands', value: 0},
      { id: 'CH', state: 'Chandigarh', value: 0 },
      { id: 'DN', state: 'Dadra and Nagar Haveli', value: 0},
      { id: 'DD', state: 'Daman and Diu', value: 0 },
      { id: 'DL', state: 'Delhi', value: 0 },
      { id: 'JK', state: 'Jammu and Kashmir', value: 0 },
      { id: 'LA', state: 'Ladakh', value: 0 },
      { id: 'LD', state: 'Lakshadweep', value: 0 },
      { id: 'PY', state: 'Puducherry', value: 0 }
    ];